#.travis.yml

language: node_js
node_js:
  - "8.10"
sudo: required
before_script:
    - "sudo chown root /opt/google/chrome/chrome-sandbox"
    - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3 
addons:
  chrome: stable
branches:
  only:
    - master

script:
  - ng lint
  - xvfb-run -a npm run test -- --single-run
  - ng build --aot --prod

after_success:
  - firebase deploy --token $FIREBASE_CI_TOKEN

notifications:
  slack: xiaochengxu1926:jCi34fSgkIcrPtRUKpzsXIIv
  email:
    on_failure: change
    on_success: change
